# Generated by Django 3.2.5 on 2022-10-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bid', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=50)),
            ],
        ),
    ]
